### Создать сотрудника
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Svetlana",
  "lastName": "Petrova",
  "department": 1,
  "salary": 1000
}
### Создать сотрудника 2
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Masha",
  "lastName": "Ivanova",
  "department": 2,
  "salary": 2000
}
### Создать сотрудника 3
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Petya",
  "lastName": "Karpov",
  "department": 3,
  "salary": 3000
}

### Создать сотрудника 4
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Rimma",
  "lastName": "Frolova",
  "department": 3,
  "salary": 1500
}
### Создать сотрудника 5
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "ivan",
  "lastName": "ivan",
  "department": 1,
  "salary": 1000
}

### Получить всех сотрудников
GET http://localhost:8080/employees

### Получить сумму зарплат всех сотрудников
GET http://localhost:8080/employees/salary/sum

### Получение сотрудника с минимальной зарплатой
GET http://localhost:8080/employee/salary/min

### Получение сотрудника с максимальной зарплатой
GET http://localhost:8080/employee/salary/max

### Получение всех сотрудников, зарплата которых больше средней зарплаты
GET http://localhost:8080/employee/high-salary

### Получить всех сотрудников по отделу номер 3
GET http://localhost:8080/department/employees?department=3

### Получить всех сотрудников по отделу номер 2
GET http://localhost:8080/department/employees?department=2

### Получить всех сотрудников по отделу номер 1
GET http://localhost:8080/department/employees?department=1

### Получаем зарплату по отделам
GET http://localhost:8080/department/1/salary/sum

### Получаем максимальную зарплату по отделу
GET http://localhost:8080/department/1/salary/max

### Получаем минимальную зарплату по отделу
GET http://localhost:8080/department/3/salary/min


